title: Brannen Hall
description: Brannen Hall's Blog
author: Brannen Hall
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/brannenghall
about: I am a undergradute student in speech–language–hearing sciences at the University of Minnesota ― Twin Cities. I enjoy playing around with LaTeX and reading about professionalization.

baseurl: "http://hurtadohall.me"
url: "http://hurtadohall.me/home"

#disqus_shortname: aboutashu

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
